version: "3.9"
services:
  api:
    container_name: api
    build: .
  database:
    container_name: database
    image: mysql:8.0
    command: "--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake"