version: "3.9"
services:
  api:
    ports:
      - 3000:3000
    volumes:
      - .:/www/app
  database:
    ports:
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: p4ssw0rd
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      